#!/bin/bash
source pwait
max_parallelism=10

# Cluster passed in from main gather
cluster=$1
namespaces=$2

# Collect all Pod logs from namespaces where MTC is installed
for ns in ${namespaces[@]}; do
  for pod in $(/usr/bin/oc get pods --no-headers --namespace $ns | awk '{print $1}'); do
    object_collection_path="/must-gather/${cluster}/namespaces/${ns}/logs/${pod}"
    mkdir -p ${object_collection_path}
    echo "[cluster=${cluster}][ns=${ns}][pod=${pod}] Collecting Pod logs..."
    /usr/bin/oc logs --all-containers --namespace ${ns} ${pod} &> "${object_collection_path}/current.log" &
    echo "[cluster=${cluster}][ns=${ns}][pod=${pod}] Collecting previous Pod logs..."
    /usr/bin/oc logs --previous --all-containers --namespace ${ns} ${pod} &> "${object_collection_path}/previous.log" & 
    pwait $max_parallelism
  done

  for kind in backup restore; do
    object_collection_path="/must-gather/${cluster}/namespaces/${ns}/logs/velero-${kind}-logs"
    mkdir -p ${object_collection_path}
    export resources=()
    for i in $(oc -n ${ns} exec $(oc -n ${ns} get po -l component=velero -o custom-columns=name:.metadata.name --no-headers) -- /bin/bash -c "/velero get ${kind}s | grep -v NAME | awk '{ print \$1 }'" | tr -d '\r'); do
      resources+=($i)
    done
    for resource in ${resources[@]}; do
      echo "[cluster=${cluster}][ns=${ns}] Gathering 'velero ${kind} logs ${resource}'"
      oc -n ${ns} exec $(oc -n ${ns} get po -l component=velero -o custom-columns=name:.metadata.name --no-headers) -- /bin/bash -c "/velero ${kind} logs $resource --timeout=30s" &> "${object_collection_path}/$resource-${kind}.log" &
      echo "[cluster=${cluster}][ns=${ns}] Gathering 'velero ${kind} describe ${resource}'"
      oc -n ${ns} exec $(oc -n ${ns} get po -l component=velero -o custom-columns=name:.metadata.name --no-headers) -- /bin/bash -c "/velero ${kind} describe $resource --details" &> "${object_collection_path}/$resource-${kind}-describe.log" &
      pwait $max_parallelism
    done
  done

  for pvr in $(oc get podvolumerestore --namespace $ns --no-headers | awk '{print $1}'); do
    restore=$(oc get podvolumerestore $pvr --namespace $ns -o jsonpath='{.metadata.labels.velero\.io/restore-name}')
    pod=$(oc get podvolumerestore $pvr --namespace $ns -o jsonpath='{.status.resticPod}')
    migplan=$(oc get restore $restore -o jsonpath='{.metadata.labels.migration\.openshift\.io/migplan-name}' --namespace $ns)
    migmigration=$(oc get restore $restore -o jsonpath='{.metadata.labels.migration\.openshift\.io/migmigration-name}' --namespace $ns)
    object_collection_path="/must-gather/migpan-${migplan}/migmigration-${migmigration}/restore-${restore}/pvr-${pvr}"
    mkdir -p ${object_collection_path}
    echo "[cluster=${cluster}][ns=${ns}][pod=${pod}] Collecting Pod logs..."
    oc logs --all-containers --namespace ${ns} ${pod} &> "${object_collection_path}/current.log" &
    echo "[cluster=${cluster}][ns=${ns}][pod=${pod}] Collecting previous Pod logs..."
    oc logs --previous --all-containers --namespace ${ns} ${pod} &> "${object_collection_path}/previous.log" & 
    pwait $max_parallelism
  done

  for pvb in $(oc get podvolumebackup --namespace $ns --no-headers | awk '{print $1}'); do
    backup=$(oc get podvolumebackup $pvb --namespace $ns -o jsonpath='{.spec.tags.backup}')
    node=$(oc get podvolumebackup $pvb --namespace $ns -o jsonpath='{.spec.node}')
    migplan=$(oc get backup $backup -o jsonpath='{.metadata.labels.migration\.openshift\.io/migplan-name}' --namespace $ns)
    migmigration=$(oc get backup $backup -o jsonpath='{.metadata.labels.migration\.openshift\.io/migmigration-name}' --namespace $ns)
    object_collection_path="/must-gather/migplan-${migplan}/migmigration-${migmigration}/backup-${backup}/pvb-${pvb}"
    mkdir -p ${object_collection_path}
    for pod in $(oc get pods -o wide --field-selector spec.nodeName=${node} --selector name=restic --no-headers --namespace $ns | awk '{print $1}'); do
      echo "[cluster=${cluster}][ns=${ns}][pod=${pod}] Collecting Pod logs..."
      oc logs --all-containers --namespace ${ns} ${pod} &> "${object_collection_path}/current.log" &
      echo "[cluster=${cluster}][ns=${ns}][pod=${pod}] Collecting previous Pod logs..."
      oc logs --previous --all-containers --namespace ${ns} ${pod} &> "${object_collection_path}/previous.log" & 
      pwait $max_parallelism
    done
  done
done

wait